[build]
  base = "triviablanca2"
  command = "npm run build"
  publish = "dist/triviablanca2"

[build.environment]
  NODE_VERSION = "18.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200