[build]
  base = "triviablanca2"
  command = "npm run build"
  publish = "dist/triviablanca2/browser"

[build.environment]
  NODE_VERSION = "20.17.0"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true