[build]
  base = "dicker-will-paradox"
  command = "npm run build"
  publish = "dist/dicker-will-paradox/browser"

[build.environment]
  NODE_VERSION = "20.17.0"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"

# Serve static assets directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = false

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200
  force = false

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false